apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: app
spec:
  type: LoadBalancer  # Changez de NodePort à LoadBalancer
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80          # Port exposé pour les utilisateurs
    targetPort: 8000  # Port utilisé par votre application dans les pods