apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://pgsql_webd:pgsql_webd@app-postgres:5432/webd"
        - name: RABBITMQ_HOST
          value: "{{ .Release.Name }}-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@{{ .Release.Name }}-rabbitmq:5672/"