apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
spec:
  replicas: {{ .Values.front.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front
    spec:
      containers:
      - name: front
        image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://127.0.0.1:30001/"
        resources:
          limits:
            cpu: {{ .Values.front.resources.limits.cpu }}
            memory: {{ .Values.front.resources.limits.memory }}
          requests:
            cpu: {{ .Values.front.resources.requests.cpu }}
            memory: {{ .Values.front.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10