apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.auth.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.auth.database }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-db
        configMap:
          name: {{ .Release.Name }}-postgres-init-script